config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'photos#index'

  get 'photos/:id', to: 'photos#next', as: 'next'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  def self.find_pics_on_page(page, amount)
    pic_range = (((page * amount) - amount) + 1) .. ((page * amount))

    Photo.where({
      id: pic_range
    })
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos
  serialize :photos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :instagram, :facebook, :twitter])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_action :set_page, only: [:index, :next]

  def index
    @pics = Photo.order(:id).limit(@pics_per_page).offset(@page * @pics_per_page)

  end

  def next
    @pics = Photo.find_pics_on_page(@page, @pics_per_page)
    render :index
  end

  private
    def set_page
      @photos = Photo.all
      @page = params[:id].to_i
      @pics_per_page = 4
      @total_pic_qty = (@photos.count / @pics_per_page)
      @page_max = @total_pic_qty + 1

      if @page != 0
        @link = @page + 1
      else
        @link = 2
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotographyPortfolio</title>
    <link href="https://fonts.googleapis.com/css?family=Libre+Baskerville" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Passion+One" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/index.html.erb
<div id="site-container">
  <div id="landing-intro">

    <div id="landing-container">
    <%= video_tag('ink_drop.mp4', autoplay: true, loop: :true, class: 'movie') %>
      <span id="name-container">
        JESUS MOLINA
      </span>
    </div>
    <span id="arrow-span">
      <%= image_tag("downwards-arrow.png", id: "arrow-pic") %>
    </span>
  </div>

  <div id="photo-container">
    <nav id="nav" class='active'>
      <span id="nav-name">
        JESUS MOLINA
      </span>
      <!-- This span underneath exists only for the on scroll underline animation -->
      <span class='nav-underline-span'></span>
    </nav>

    <div id="lower-main-container">

     <!--  <div id="left-click">
        <% if @page > 1 %>
          <%= link_to "PREV", (next_path(@link - 2) + "/#individual-photo") %>
        <% end %>
      </div> -->

      <div id="sidescrolling-container-buffer">
        <div id="sidescrolling-container">
          <% @pics.each do |photo| %>
            <% @pic_id = photo.id%>
            <% @photo_url = Photo.where(id: @pic_id)[0].url %>
            <% @photo_position = photo.landscape %>
            <div class="individual-photo-div" data-url="<%= @photo_url %>" data-position="<%= @photo_position %>"  data-page-max="<%= @page_max %>">

              <img class="actual-image" src="<%= photo.url %>" height='250px' width="250px">
              <span id="photo-title"><%= photo.title.upcase %></span>
            </div>
          <% end %>
        </div>
      </div>

      <!-- These are only necessary if JavaScript is off in the browser.  Therefore they will remain here for the time being -->

      <!-- <div id="right-click">
        <% if @page < @page_max %>
          <%= link_to "NEXT", (next_path(@link) + "/#individual-photo"), id: "next_button" %>
        <% end %>
      </div> -->

      <!-- The Modal -->
      <div id="myModal-flex" class="modal-flex">

        <!-- Modal content -->
        <div class="modal-content-flex">

        <!-- THIS IS IMPORTANT: .close-flex should have an &times; inside the html when the user clicks an image -->

          <span class="close-flex"></span>
          <img id='modal-image'>
        </div>
      </div>

      <footer id="contact-footer">
        <span id="footer-overhead-line-span-container">
          <span class="footer-overhead-line-span"></span>
        </span>
        <span id="footer-span" class="footer-span-direction">
          CONTACT
          <span id="hidden-social" class='hidden-social-invisible'>
            <a class='social_media_link' href='#' target='_blank'><img id='facebook' class='social_media_icon' src='../assets/social_media_icons/white_fb_transparent_circle.png'></a>
            <a class='social_media_link' href='https://www.google.com' target='_blank'><img id='twitter' class='social_media_icon' src='../assets/social_media_icons/white_twitter_transparent_circle.png'></a>
            <a class='social_media_link' href='#' target='_blank'><img id='instagram' class='social_media_icon' src='../assets/social_media_icons/white_ig_transparent_circle.png'></a>
            <a class='social_media_link' href='https://www.google.com' target='_blank'><img id='mail' class='social_media_icon' src='../assets/social_media_icons/white_mail_transparent_circle.png'></a>
          </span>

          <span id="contact-underline-span">
          </span>
        <span>
      </footer>

    </div>
  </div>
</div>